-- Row Level Security generated by vibeproof Fix Pack
-- Source: supabase/migrations/001_schema.sql
-- Generated: 2026-09-17T16:50:49.690Z
--
-- Read this before running it. Your own policies are left in place and listed
-- as comments to review. Run it against a branch or a copy first.
-- Apply with:  psql "$DATABASE_URL" -f rls_policies.sql
--         or:  supabase db push  after saving it as a migration.

begin;

-- profiles
-- The primary key references auth.users, so a row is the user.
-- Ownership: self via id (confidence: high)

alter table public."profiles" enable row level security;
alter table public."profiles" force row level security;   -- applies to the table owner too

drop policy if exists "vibeproof_owner_select" on public."profiles";
drop policy if exists "vibeproof_owner_write" on public."profiles";
drop policy if exists "vibeproof_deny_all" on public."profiles";

create policy "vibeproof_owner_select" on public."profiles"
  for select to authenticated using ( (select auth.uid()) = "id" );

create policy "vibeproof_owner_write" on public."profiles"
  for all to authenticated
  using ( (select auth.uid()) = "id" )
  with check ( (select auth.uid()) = "id" );

-- Row Level Security is not enough on its own: table privileges are checked first.
revoke all on public."profiles" from anon;
grant select, insert, update, delete on public."profiles" to authenticated;
-- If this table holds data every visitor should read (public catalogue, blog posts),
-- add exactly this and nothing more:  grant select on public."profiles" to anon;
--   create policy "public read" on public."profiles" for select to anon using ( true );

-- organizations
-- No column identifies an owner. This table needs a decision from you.
-- REVIEW REQUIRED: vibeproof could not find an owner column. The policy below
--   denies everything, which is the safe default. Replace it once you decide who may read this table.

alter table public."organizations" enable row level security;
alter table public."organizations" force row level security;   -- applies to the table owner too

drop policy if exists "vibeproof_owner_select" on public."organizations";
drop policy if exists "vibeproof_owner_write" on public."organizations";
drop policy if exists "vibeproof_deny_all" on public."organizations";

-- No owner column found, so this denies everything. Nothing can read or write
-- this table through the API until you replace this policy deliberately.
create policy "vibeproof_deny_all" on public."organizations"
  for all to authenticated, anon using ( false ) with check ( false );

-- Row Level Security is not enough on its own: table privileges are checked first.
revoke all on public."organizations" from anon;
grant select, insert, update, delete on public."organizations" to authenticated;

-- org_members
-- user_id references auth.users directly.
-- Ownership: user via user_id (confidence: high)

alter table public."org_members" enable row level security;
alter table public."org_members" force row level security;   -- applies to the table owner too

drop policy if exists "vibeproof_owner_select" on public."org_members";
drop policy if exists "vibeproof_owner_write" on public."org_members";
drop policy if exists "vibeproof_deny_all" on public."org_members";

create policy "vibeproof_owner_select" on public."org_members"
  for select to authenticated using ( (select auth.uid()) = "user_id" );

create policy "vibeproof_owner_write" on public."org_members"
  for all to authenticated
  using ( (select auth.uid()) = "user_id" )
  with check ( (select auth.uid()) = "user_id" );

-- Row Level Security is not enough on its own: table privileges are checked first.
revoke all on public."org_members" from anon;
grant select, insert, update, delete on public."org_members" to authenticated;
-- If this table holds data every visitor should read (public catalogue, blog posts),
-- add exactly this and nothing more:  grant select on public."org_members" to anon;
--   create policy "public read" on public."org_members" for select to anon using ( true );

-- projects
-- Column org_id points at an organisation, so access is decided by membership.
-- Ownership: tenant via org_id (confidence: medium)

alter table public."projects" enable row level security;
alter table public."projects" force row level security;   -- applies to the table owner too

drop policy if exists "vibeproof_owner_select" on public."projects";
drop policy if exists "vibeproof_owner_write" on public."projects";
drop policy if exists "vibeproof_deny_all" on public."projects";

-- Membership verified from your schema: org_members.user_id -> org_members.org_id
create policy "vibeproof_owner_select" on public."projects"
  for select to authenticated using ( "org_id" in ( select m."org_id" from public."org_members" m where m."user_id" = (select auth.uid()) ) );

create policy "vibeproof_owner_write" on public."projects"
  for all to authenticated using ( "org_id" in ( select m."org_id" from public."org_members" m where m."user_id" = (select auth.uid()) ) ) with check ( "org_id" in ( select m."org_id" from public."org_members" m where m."user_id" = (select auth.uid()) ) );

-- Row Level Security is not enough on its own: table privileges are checked first.
revoke all on public."projects" from anon;
grant select, insert, update, delete on public."projects" to authenticated;
-- If this table holds data every visitor should read (public catalogue, blog posts),
-- add exactly this and nothing more:  grant select on public."projects" to anon;
--   create policy "public read" on public."projects" for select to anon using ( true );

-- api_keys
-- Column org_id points at an organisation, so access is decided by membership.
-- Ownership: tenant via org_id (confidence: medium)

alter table public."api_keys" enable row level security;
alter table public."api_keys" force row level security;   -- applies to the table owner too

drop policy if exists "vibeproof_owner_select" on public."api_keys";
drop policy if exists "vibeproof_owner_write" on public."api_keys";
drop policy if exists "vibeproof_deny_all" on public."api_keys";

-- Membership verified from your schema: org_members.user_id -> org_members.org_id
create policy "vibeproof_owner_select" on public."api_keys"
  for select to authenticated using ( "org_id" in ( select m."org_id" from public."org_members" m where m."user_id" = (select auth.uid()) ) );

create policy "vibeproof_owner_write" on public."api_keys"
  for all to authenticated using ( "org_id" in ( select m."org_id" from public."org_members" m where m."user_id" = (select auth.uid()) ) ) with check ( "org_id" in ( select m."org_id" from public."org_members" m where m."user_id" = (select auth.uid()) ) );

-- Row Level Security is not enough on its own: table privileges are checked first.
revoke all on public."api_keys" from anon;
grant select, insert, update, delete on public."api_keys" to authenticated;
-- If this table holds data every visitor should read (public catalogue, blog posts),
-- add exactly this and nothing more:  grant select on public."api_keys" to anon;
--   create policy "public read" on public."api_keys" for select to anon using ( true );

-- invoices
-- Column org_id points at an organisation, so access is decided by membership.
-- Ownership: tenant via org_id (confidence: medium)

alter table public."invoices" enable row level security;
alter table public."invoices" force row level security;   -- applies to the table owner too

drop policy if exists "vibeproof_owner_select" on public."invoices";
drop policy if exists "vibeproof_owner_write" on public."invoices";
drop policy if exists "vibeproof_deny_all" on public."invoices";

-- Membership verified from your schema: org_members.user_id -> org_members.org_id
create policy "vibeproof_owner_select" on public."invoices"
  for select to authenticated using ( "org_id" in ( select m."org_id" from public."org_members" m where m."user_id" = (select auth.uid()) ) );

create policy "vibeproof_owner_write" on public."invoices"
  for all to authenticated using ( "org_id" in ( select m."org_id" from public."org_members" m where m."user_id" = (select auth.uid()) ) ) with check ( "org_id" in ( select m."org_id" from public."org_members" m where m."user_id" = (select auth.uid()) ) );

-- Row Level Security is not enough on its own: table privileges are checked first.
revoke all on public."invoices" from anon;
grant select, insert, update, delete on public."invoices" to authenticated;
-- If this table holds data every visitor should read (public catalogue, blog posts),
-- add exactly this and nothing more:  grant select on public."invoices" to anon;
--   create policy "public read" on public."invoices" for select to anon using ( true );

-- notes
-- user_id references auth.users directly.
-- Ownership: user via user_id (confidence: high)

alter table public."notes" enable row level security;
alter table public."notes" force row level security;   -- applies to the table owner too

drop policy if exists "vibeproof_owner_select" on public."notes";
drop policy if exists "vibeproof_owner_write" on public."notes";
drop policy if exists "vibeproof_deny_all" on public."notes";

create policy "vibeproof_owner_select" on public."notes"
  for select to authenticated using ( (select auth.uid()) = "user_id" );

create policy "vibeproof_owner_write" on public."notes"
  for all to authenticated
  using ( (select auth.uid()) = "user_id" )
  with check ( (select auth.uid()) = "user_id" );

-- Row Level Security is not enough on its own: table privileges are checked first.
revoke all on public."notes" from anon;
grant select, insert, update, delete on public."notes" to authenticated;
-- If this table holds data every visitor should read (public catalogue, blog posts),
-- add exactly this and nothing more:  grant select on public."notes" to anon;
--   create policy "public read" on public."notes" for select to anon using ( true );

-- plans
-- No column identifies an owner. This table needs a decision from you.
-- REVIEW REQUIRED: vibeproof could not find an owner column. The policy below
--   denies everything, which is the safe default. Replace it once you decide who may read this table.

alter table public."plans" enable row level security;
alter table public."plans" force row level security;   -- applies to the table owner too

drop policy if exists "vibeproof_owner_select" on public."plans";
drop policy if exists "vibeproof_owner_write" on public."plans";
drop policy if exists "vibeproof_deny_all" on public."plans";

-- No owner column found, so this denies everything. Nothing can read or write
-- this table through the API until you replace this policy deliberately.
create policy "vibeproof_deny_all" on public."plans"
  for all to authenticated, anon using ( false ) with check ( false );

-- Row Level Security is not enough on its own: table privileges are checked first.
revoke all on public."plans" from anon;
grant select, insert, update, delete on public."plans" to authenticated;

-- events
-- Column user_id names a user and is the usual ownership column.
-- Ownership: user via user_id (confidence: medium)

alter table public."events" enable row level security;
alter table public."events" force row level security;   -- applies to the table owner too

drop policy if exists "vibeproof_owner_select" on public."events";
drop policy if exists "vibeproof_owner_write" on public."events";
drop policy if exists "vibeproof_deny_all" on public."events";

-- You already have 1 policy(ies) on this table. They are
-- left in place. Policies combine with OR, so a permissive one still grants
-- access even after the policy below is added. Review these, and drop the
-- ones you did not mean to keep:
--   drop policy if exists "read all events" on public."events";   <-- passes for everyone, almost certainly drop this
-- Or re-run with --replace-existing to have them dropped for you.

create policy "vibeproof_owner_select" on public."events"
  for select to authenticated using ( (select auth.uid()) = "user_id" );

create policy "vibeproof_owner_write" on public."events"
  for all to authenticated
  using ( (select auth.uid()) = "user_id" )
  with check ( (select auth.uid()) = "user_id" );

-- Row Level Security is not enough on its own: table privileges are checked first.
revoke all on public."events" from anon;
grant select, insert, update, delete on public."events" to authenticated;
-- If this table holds data every visitor should read (public catalogue, blog posts),
-- add exactly this and nothing more:  grant select on public."events" to anon;
--   create policy "public read" on public."events" for select to anon using ( true );

commit;

-- After applying, prove it worked:  node rls_tests.mjs